### PR TITLE
adding support for apm_jvm_metric and instance scope alerts

### LINKED ISSUE #19: Cannot create newrelic_alert_condition due to absence of violation_close_timer
Hi there,

### Terraform Version
I'm using Terraform v0.10.6

### Affected Resource(s)
- newrelic_alert_condition

### Terraform Configuration Files
```resource "newrelic_alert_condition" "some_threadpool_alert_condition" {
  policy_id                   = "${newrelic_alert_policy.some_threadpool_alert_policy.id}"
  name                        = "${upper(terraform.workspace)}_Some_Threads"
  type                        = "apm_app_metric"
  entities                    = ["${data.newrelic_application.some_app.id}"]
  metric                      = "user_defined"
  condition_scope             = "instance"
  user_defined_metric         = "JmxBuiltIn/ThreadPool/\"some-thread-pool\"/Active"
  user_defined_value_function = "average"

  term {
    duration      = 5
    operator      = "above"
    priority      = "warning"
    threshold     = "150"
    time_function = "all"
  }

  term {
    duration      = 5
    operator      = "above"
    priority      = "critical"
    threshold     = "170"
    time_function = "all"
  }
}
```

### Expected Behaviour
The terraform plan came back clean, so I was not expecting any issues when running the apply.  The apply should have created the newrelic_alert_condition.

### Actual Behaviour
All other terraform new relic resources were created correctly, but all of my newrelic_alert_condition resources failed with the message 

```* newrelic_alert_condition.some_threadpool_alert_condition: 1 error(s) occurred: newrelic_alert_condition.some_threadpool_alert_condition: `violation_close_timer` (in hours) must be present and one of: 1, 2, 4, 8, 12, 24.```

I attempted to add violation_close_timer to the config, thinking that it was a config parameter that I missed off, but when I reran plan I got this message:
```newrelic_alert_condition.some_threadpool_alert_condition: : invalid or unknown key: violation_close_timer```

I then attempted to add violation_close_timer inside the term declaration, but when I reran the plan I got this message:

```newrelic_alert_condition.some_threadpool_alert_condition: term.0: invalid or unknown key: violation_close_timer```

### Steps to Reproduce
1. `terraform apply`

### PR DESCRIPTION
**Pull request by acondrat**
Depends on https://github.com/paultyng/go-newrelic/pull/13 and fixes #19

### CODE REVIEW

**Comment by paultyng** [comment]
merged the dependent commit and cut a new release

**Comment by ryangardner** [comment]
@radeksimko is there anything the community can do to help get these PRs reviewed / merged? Is there any chance someone from new relic could be added to the list of committers?

**Comment by smithclay** [comment]
Think this is really close to being ready for merging, working through the PR backlog this week:
* rebase against the latest `master` branch, which has the latest version of the `go-newrelic` sdk.
* add a quick acceptance test for the two new attribute types in `resource_newrelic_alert_condition_test.go`—should be really fast just two additional `TestCheckResourceAttr` statments for the new attributes. [Here's an example of one](https://github.com/acondrat/terraform-provider-newrelic/blob/14e15d86401e4cdd6b8cea7f8c5e7f3940169ddb/newrelic/resource_newrelic_alert_condition_test.go#L28-L29) for another attribute on the same resource.

thanks!

**Comment by acondrat** [comment]
@smithclay could you please have a look?

PS: sorry if it does not look right, I'm not a go developer.

**Comment by smithclay** [comment]
Think you'll also need to update the resource defined in the `testAccCheckNewRelicAlertConditionConfig` function with the new attributes: https://github.com/acondrat/terraform-provider-newrelic/blob/f535e788cb790ef0f329df4f034ba01b97ab1d41/newrelic/resource_newrelic_alert_condition_test.go#L184-L200`

At a high level, the`TestCheckResourceAttr` function verifies the attributes match the resource defined in `testAccCheckNewRelicAlertConditionConfig` and needs to be updated in both places with the new attributes.

**Comment by acondrat** [comment]
@smithclay As far as I understand,  [instance scope alerts are for Java agents only](https://docs.newrelic.com/docs/alerts/new-relic-alerts/defining-conditions/scope-alert-thresholds-specific-instances)
The test application that get created is using a go-agent. Example:
```      
"name": "tf_test_ke6wz8sc0g",
"language": "go",
```

I'd assume I need a `"language": "java"` application to be able to test this properly. I tried to add a test for instance scope alert in https://github.com/terraform-providers/terraform-provider-newrelic/pull/24/commits/b541934f2ceb1ebf338ae4f50d3829eeb2b60bcd but there is this problem:
```
=== RUN   TestAccNewRelicAlertCondition_InstanceScope
--- FAIL: TestAccNewRelicAlertCondition_InstanceScope (5.17s)
	testing.go:435: Step 0 error: Error applying: 1 error(s) occurred:

		* newrelic_alert_condition.foo: 1 error(s) occurred:

		* newrelic_alert_condition.foo: All entities must be Java agents. Non-Java id(s): 95446106.
```

I'm struggling to understand how the test application is created. Maybe you can point to the right place for changing agent language. Seems like right now it uses the default in https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/vendor/github.com/newrelic/go-agent/internal_config.go#L51

**Comment by smithclay** [comment]
@acondrat Unfortunately it seems like it's not going to be easy to change the language agent. 

Currently, [the test provider actually uses the New Relic Go agent SDK to create an application](https://github.com/terraform-providers/terraform-provider-newrelic/blob/master/newrelic/provider_test.go#L48-L52) in `provider_test.go`.... The test application type is go because it's actually creating a go application. 

There is an internal config setting in the [Go agent SDK that specifies the language type](https://github.com/newrelic/go-agent/blob/master/internal_config.go#L118) but (understandably and for good reasons) it can't be overridden. 

With this in mind, doesn't seem like it's going to be easy to create an integration test for these attributes until there's a way to create multiple types of test applications (I can't think of a decent way to do this yet that doesn't involve bundling every New Relic Agent SDK).

Fine moving forward on this PR without the tests, thanks for the discovery and I learned a lot about the test providers going through this code.

**Comment by acondrat** [comment]
@smithclay I removed the failing test. Please let me know if there are any other changes required before it can be merged.

**Pull request merged**
