### PR TITLE
Check if alert policy exists before retrieving

### PR DESCRIPTION
**Pull request by ianrayns**
Addressing #57

### CODE REVIEW

**Comment by paultyng** [comment]
Could we simulate this behavior in some acceptance tests by using bad / hardcoded policy IDs? Maybe you can try to write one? If not, I can maybe take a look later this week to get some test coverage on this.

**Comment by tyrsius** [comment]
@ianrayns @bridgetlane Is there something holding up the merge on this? I am blocked on this error

**Comment by bridgetlane** [comment]
@tyrsius based on @paultyng's comment sounds like we need some acceptance tests before merge

**Comment by tyrsius** [comment]
@bridgetlane This pull request hasn't had any activity in 6 months. Meanwhile a deployment-blocking bug persists.

If you keep waiting for tests I don't see this bug ever getting fixed.
If you merge this pull request and the fix doesn't work affected users will be no worse off.
If you merge this pull request and the fix does work affected users will no longer be in a _undeployable_ state.

**Comment by timonwalkley** [comment]
Hey @paultyng, can anything be done to push this one along?

Many thanks!

**Comment by jhoward321** [comment]
Any updates on this?

**Comment by SethDG** [comment]
@paultyng @bridgetlane This issue is currently blocking one of our deploys.  Is there anything we can do to help out?  I wouldn't even know where to begin with a test, but if you have some suggestions or advice, I can certainly try.

**Pull request merged**
