### PR TITLE
Fixed Issue #3 (Make resource_newrelic_alert_condition enabled status configurable) & #55 (Modifying an alert policy recreates resource)

### PR DESCRIPTION
**Pull request by sgsiebers**
* Consumed updated go-newrelic API for UpdateAlertPolicy (https://github.com/paultyng/go-newrelic/pull/25)
* Implemented alert_policy resource updates rather than forcing delete/add each time
* Fixed Issue #3: Make resource_newrelic_alert_condition enabled status configurable (https://github.com/terraform-providers/terraform-provider-newrelic/issues/3)

### CODE REVIEW

**Comment by sgsiebers** [comment]
I've fixed CI build issues with vendor dependencies.  This should be ready for review and merging.  Thanks!

**Comment by ianrayns** [comment]
Awesome, looks like this fixes #55 🎉

**Comment by sgsiebers** [comment]
@ianrayns I've rebased everything off latest upstream changes from master.  I think this is good to go.

**Comment by sgsiebers** [comment]
Just checking back on this PR.  Anything else you need from be before this can be merged?

**Comment by sgsiebers** [comment]
Looking at this PR again, I realize it's dragging a lot of unrelated changes when I rebased off upstream to resolve merge conflicts.  @ianrayns, or other maintainers, would it help if I cancel this PR and submit a fresh one based off a clean upstream copy?  I'm happy to do that if I can get some attention on getting these fixes merged to master soon after.  The change here is fairly small, and I've been using successfully on my personal branch for a while now.  I'm new to this community, so please advise how I can help.  Thanks!

**Comment by bridgetlane** [comment]
@sgsiebers yeah a fresh PR with just your changes would be great. Functionality looks good.

**Comment by sgsiebers** [comment]
Ok, thanks @bridgetlane, I'll split these up into separate PR's to keep the changes isolated.

**Pull request closed without merging**
