### PR TITLE
Add support for integration_provider when creating infra alerts

### PR DESCRIPTION
**Pull request by ianrayns**
Addressing #35 

There hasn't been much activity on GH-38, and we need this functionality (sorry if this treads on peoples toes!)

Couldn't add any integration tests as I wasn't sure if there are any custom integrations set up in the account it runs against, but have verified that this feature is working as expected.

### CODE REVIEW

**Comment by ianrayns** [comment]
Having trouble getting the build passing - seems to be a problem with Linux vs Windows line endings. Any help appreciated 👍

**Comment by ianrayns** [comment]
Is this repo still being maintained? Would really appreciate some eyes on this PR so we can get it into the next release

**Comment by bridgetlane** [comment]
Hi @ianrayns! Looks good to me. Would be great to see this field added to the tests, and an addition to the docs located at website/docs/r/infra_alert_condition.html.markdown. Let me know if you need any help with this. Thanks for contributing!

**Comment by Constantin07** [comment]
When this PR will be merged ?

**Comment by timonwalkley** [comment]
+1, can we get this merged please!

**Comment by paultyng** [comment]
No custom providers are setup on this account currently, we could set one up if there is a free option. I'm not really familiar with this feature, is there a way I could set it up?

**Comment by paultyng** [comment]
Tests should be added to this, but I'll merge it for now as it doesn't seem to affect the existing functionality and acc tests pass. Can you add some tests and confirm this works @ianrayns ? Or give me some steps to set this up on our account?

**Comment by paultyng** [comment]
Let me poke around in the UI and see what I can find.

**Comment by paultyng** [comment]
Yeah, looks like I can't do this in my account. What we typically do in these situations (see things like direct connect's in AWS, etc), is still write the tests, and someone who can test it, run it and post the acceptance test results in the PR, for example: https://github.com/terraform-providers/terraform-provider-aws/pull/5886

You'll see that the test skips if an environment variable isn't set (in this case potentially the integration provider or something): https://github.com/terraform-providers/terraform-provider-aws/pull/5886/files#diff-11893383ea8f55fabea5ee47e0f73b3cR19

**Comment by chadbean** [comment]
thanks @paultyng. I just created a PR (https://github.com/ianrayns/terraform-provider-newrelic/pull/1) against @ianrayns branch which adds a test using an environment variable.

**Comment by ianrayns** [comment]
Thanks @chadbean for adding the test!
```
=== RUN   TestAccNewRelicInfraAlertCondition_IntegrationProvider
--- PASS: TestAccNewRelicInfraAlertCondition_IntegrationProvider (3.52s)
```

**Pull request merged**
