### PR TITLE
Adds validation for alerts policy names

### PR DESCRIPTION
**Pull request by t0astbandit**
As requested in #79 
Also adds tests

### CODE REVIEW

**Comment by t0astbandit** [comment]
@paultyng we've corrected the merge conflicts.  When you have a moment would you mind reviewing this please?

**Comment by paultyng** [comment]
Sorry for the delay here, things are taking a little longer as we try to ship 0.12.

**Comment by t0astbandit** [comment]
Hey there, it's me again. I know you're a busy fella but I'm wondering if we can get this merged.

**Comment by ctrombley** [comment]
Thanks @t0astbandit !

**Pull request merged**
